### ISSUE TITLE
Suggestion: Don't delete the previous releases!

### ISSUE THREAD

**Issue by VulcanShot** [PlayerHOI/IWFC#8] opened 2022-01-19 19:33 UTC
I've noticed that only the latest release is available. In the current state of the application, it is reasonable that the older versions are not available, as they may have many bugs. However, I suggest not deleting the previous releases as some users might want to get certain versions of the application in the future.

**Comment by PlayerHOI** [comment] 2022-01-21 08:58
Noted, the previous version was deleted since it contained a lot of functionality for SVG files that didn't work which was resolved in the next release and was intended to work from the get go.

**Closed by PlayerHOI** 2022-01-21 08:58 UTC
