### ISSUE TITLE
only large flag created for HOI4 flags

### ISSUE THREAD

**Issue by ScrewDriverPizzaCoder** [PlayerHOI/IWFC#3] opened 2022-01-15 20:34 UTC

**Comment by PlayerHOI** [comment] 2022-01-18 08:07
Can you please provide more details? Were you using a local image or an image from the web? Provide a list of actions you've done to reproduce the problem?

**Comment by VulcanShot** [comment] 2022-01-18 17:28
I had the same problem in the first version. However, in the new release everything seems to be fine :)

**Comment by VulcanShot** [comment] 2022-01-21 21:29
I'd suggest closing this issue.

**Comment by PlayerHOI** [comment] 2022-01-21 22:01
> I'd suggest closing this issue.

Yeah seems dead...

**Closed by PlayerHOI** 2022-01-21 22:01 UTC
Labels: Portential Bug
